# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.11']
    runs-on: ubuntu-latest
    timeout-minutes: 5

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
              
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run Ruff
        run: ruff check --output-format=github .

      - name: Run Black
        run: black --check --diff .

      - name: Run Bandit scan
        run: bandit -c pyproject.toml -r .

      - name: Install Mosquitto
        run: |
          sudo apt-get install -y mosquitto

      - name: Run unit and integration tests
        run: |
          bash tests/integration/mosquitto/run_mosquitto.sh
          sleep 3
          bash run_tests.sh

      - name: Run code coverage
        run: |
          coverage run -m unittest discover
          coverage report -m
